AWSTemplateFormatVersion: "2010-09-09"
Description: >
  IAM user with CloudFormation admin + IAM management rights.
  Outputs access keys for programmatic use.

Resources:
  CfnAdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: cfn-admin-user

  CfnAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-admin-full
      Users: [!Ref CfnAdminUser]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Full CloudFormation control
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource: "*"

          # Create and manage IAM users, roles, and keys (needed when CFN templates create IAM resources)
          - Effect: Allow
            Action:
              - iam:*
            Resource: "*"

          # Pass roles to CloudFormation-created resources
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: "*"

  CfnAdminAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref CfnAdminUser
      Status: Active

Outputs:
  AccessKeyId:
    Description: Access key ID for the new IAM user
    Value: !Ref CfnAdminAccessKey
  SecretAccessKey:
    Description: Secret access key for the new IAM user
    Value: !GetAtt CfnAdminAccessKey.SecretAccessKey
  UserName:
    Description: IAM user name
    Value: !Ref CfnAdminUser
